### ISSUE TITLE
The AppConfig.plist is missing

### ISSUE THREAD

**Issue by LearnWithTung** [nodediggity/box-office#11]
Hello, 
the file is missing in your project. Could you please provide it ?

**Comment by nodediggity** [comment]
Hey 👋🏼

You'll need to obtain a free secret key from [here](https://developers.themoviedb.org/3/getting-started/authentication)

Then you can add the file as below to the root 👍 

```
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>secret</key>
	<string>_YOUR SECRET KEY_</string>
</dict>
</plist>
```

**Comment by LearnWithTung** [comment]
Thank a lot !
